language: node_js

os: osx
  osx_image: xcode9.4
  language: node_js
  node_js: "12.14.0"
  env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install yarn;
    fi
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      yarn install;
      yarn package;
    else
      npm install;
      npm run package-win;
    fi
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
notifications:
  webhooks:
    urls:
      - https://open.feishu.cn/officialapp/notify/dd6698e1132974790e9996e8181d32496d4ffc1e9fc64395763fd87a7abdf872
    on_success: always # default: always
    on_failure: always # default: always
    on_start: never # default: never
    on_cancel: never # default: always
    on_error: always # default: always
